model:
  name: FNOArch
  params:
    dimension: 3
    nr_fno_layers: 6
    nr_decoder_layers: 2
    nr_ff_blocks: 2
    modes: [16, 16, 16]
    functional: false
    weight_sharing: false
    batch_norm: false
    dropout: false

training:
  loss: MaskedMSELoss
  optimizer:
    name: AdamW
    params:
      lr: 2.5e-3
      weight_decay: 1.0e-4
  scheduler:
    name: CosineWithWarmupScheduler
    params:
      warmup_steps: 500
      min_lambda: 0.05

data:
  batch_size: 16
  train_path: "/home/vault/iwia/iwia057h/data/scaled/train"
  test_path: "/home/vault/iwia/iwia057h/data/scaled/test"
  validation_path: "/home/vault/iwia/iwia057h/data/validation"
  dataset_params:
    fast: false
    rotate: false
    masking: true
    scaling: true

runtime:
  epochs: 75
  mode: eval  # Can be 'train' or 'eval'
  checkpoint:
    load: true
    save_dir: "output/"
    name: "FNO_6l_16"